language: python
sudo: false
python:
  - "2.7"
virtualenv:
    system_site_packages: true

addons:
  apt:
    packages:
    - git

before_install:
  # Set up anaconda
  - wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - export PYTHONPATH=$TRAVIS_BUILD_DIR/DataDrivenEstimator:$PYTHONPATH
  # Update conda itself
  - conda update --yes conda
  - cd ..
  - cd DataDrivenEstimator

install:
  - conda env create -f envs/environment.yaml
  - source activate dde_env
  - conda list
  - export KERAS_BACKEND=theano

script: 
  - make test-cnn

