# For conda build
package:
  name: dde
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }} # set by build.sh, which gets from rmgpy/__init__.py

source:
  path: .

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  noarch: generic

requirements:
  build:
    - python

  run:
    - python
    - nose
    - keras=1.2.2
    - tqdm
    - pymongo
    - theano=0.9.0
    - pydot-ng
    - rmg # We need to remove this when building for use in RMG

test:
  source_files:
    - '*'
  requires:
    - nose
  imports:
    - dde
  commands:
    - export KERAS_BACKEND=theano
    - make -C $SRC_DIR test-cnn [unix]

about:
  home: https://github.com/ReactionMechanismGenerator/DataDrivenEstimator
  license: MIT
  summary: "A data driven estimator for molecular thermochemistry and kinetics"
